[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Explicitly serve favicon without redirects
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

# Fix MIME types for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Fix MIME types for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

# Fix MIME types for favicon
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400"
